/**
 * Return an array of the return values generated by calling the given function for each element in the given array
 * @param {*[]} arr - array with elements to be consumed by the given function
 * @param {function} fun - function that will be called for each element in arr
 * @param {number} i - current index of arr
 * @param {*[]} result - results of calling fun for each element in arr
 */
const runOnEach = (arr = [], fun, i = 0, result = []) => {
  if (!fun || i >= arr.length) return result;

  result.push(fun(arr[i], i));
  return runOnEach(arr, fun, i + 1, result);
};

module.exports = {
  runOnEach,
};
